version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.2
    working_directory: /go/src/github.com/sawadashota/waitopen
    steps:
      - checkout
      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v ./...
